CSVS-93 Implementation of EventHandler was changed
bwsw/cs-vault-server pull request #102
Opened 2018-01-17 11:00 UTC by MedvedevBW

2018-01-19 07:51 UTC, placccebo requested changes

2018-01-19 07:51 UTC, placccebo commented on src/main/scala/com/bwsw/cloudstack/vault/server/cloudstack/util/CloudStackEventHandler.scala
> +  private def runEventHandle(leaderLatch: InterruptableCountDawnLatch,
runEventHandling

2018-01-19 07:51 UTC, placccebo commented on src/main/scala/com/bwsw/cloudstack/vault/server/cloudstack/util/CloudStackEventHandler.scala
> +                             eventHandleFunc: (UUID) => Unit): Unit = {
eventHandlingFunc

2018-01-19 07:51 UTC, placccebo commented on src/test/scala/com/bwsw/cloudstack/vault/server/cloudstack/util/CloudStackEventHandlerTestSuite.scala
> +    "if controller thrown an exception" in {
fix description (English)

2018-01-19 07:51 UTC, placccebo commented on src/test/scala/com/bwsw/cloudstack/vault/server/cloudstack/util/CloudStackEventHandlerTestSuite.scala
> +  "handle" should "handle event such as unknown event if JsonSerializer thrown JsonParseException" in {
fix description (English)

2018-01-19 07:51 UTC, placccebo commented on src/test/scala/com/bwsw/cloudstack/vault/server/cloudstack/util/CloudStackEventHandlerTestSuite.scala
> +  "handle" should "change input flag to false and return empty outputEnvelopes list " +
fix description (English)

2018-01-22 02:29 UTC, MedvedevBW commented on src/main/scala/com/bwsw/cloudstack/vault/server/cloudstack/util/CloudStackEventHandler.scala
> +  private def runEventHandle(leaderLatch: InterruptableCountDawnLatch,
ok

2018-01-22 02:29 UTC, MedvedevBW commented on src/main/scala/com/bwsw/cloudstack/vault/server/cloudstack/util/CloudStackEventHandler.scala
> +                             eventHandleFunc: (UUID) => Unit): Unit = {
ok

2018-01-22 04:24 UTC, MedvedevBW commented on src/test/scala/com/bwsw/cloudstack/vault/server/cloudstack/util/CloudStackEventHandlerTestSuite.scala
> +  "handle" should "change input flag to false and return empty outputEnvelopes list " +
ok

2018-01-22 04:24 UTC, MedvedevBW commented on src/test/scala/com/bwsw/cloudstack/vault/server/cloudstack/util/CloudStackEventHandlerTestSuite.scala
> +  "handle" should "handle event such as unknown event if JsonSerializer thrown JsonParseException" in {
ok

2018-01-22 04:24 UTC, MedvedevBW commented on src/test/scala/com/bwsw/cloudstack/vault/server/cloudstack/util/CloudStackEventHandlerTestSuite.scala
> +    "if controller thrown an exception" in {
ok

2018-01-22 04:37 UTC, placccebo approved these changes

2018-01-22 04:44 UTC, merged