CSVS-94 CloudStackService was refactored for using DAO
bwsw/cs-vault-server pull request #108
Opened 2018-01-19 11:51 UTC by MedvedevBW

2018-01-19 11:51 UTC, MedvedevBW commented
@placccebo

2018-01-22 05:13 UTC, placccebo requested changes

2018-01-22 05:13 UTC, placccebo commented on src/main/scala/com/bwsw/cloudstack/vault/server/cloudstack/CloudStackService.scala
> +  def getVaultAccountTags(accountId: UUID): Set[VaultTag] = {
method description doesn't correspond to method name/signature, also I doubt that "VaultTag" name is right because tag relates to cloudstack rather than vault

2018-01-22 05:13 UTC, placccebo commented on src/test/scala/com/bwsw/cloudstack/vault/server/mocks/requests/MockTagCreateRequest.scala
> +  def requestIsEqualTo(request: TagCreateRequest): Boolean = {
rename to "requestEqualsTo"

2018-01-22 06:40 UTC, MedvedevBW commented on src/main/scala/com/bwsw/cloudstack/vault/server/cloudstack/CloudStackService.scala
> +  def getVaultAccountTags(accountId: UUID): Set[VaultTag] = {
Yes, but this tag keeping the information from Vault

2018-01-22 08:57 UTC, MedvedevBW commented on src/test/scala/com/bwsw/cloudstack/vault/server/mocks/requests/MockTagCreateRequest.scala
> +  def requestIsEqualTo(request: TagCreateRequest): Boolean = {
ok

2018-01-23 03:30 UTC, placccebo requested changes

2018-01-23 03:30 UTC, placccebo commented on src/main/scala/com/bwsw/cloudstack/vault/server/cloudstack/CloudStackService.scala
> +  def getAccountTags(accountId: UUID): Set[Tag] = {
get rid of unused methods

2018-01-23 05:54 UTC, placccebo approved these changes

2018-01-23 05:54 UTC, merged