CSVS-109 Integration tests were implemented for read/write policies
bwsw/cs-vault-server pull request #119
Opened 2018-01-24 10:08 UTC by MedvedevBW

2018-01-24 10:08 UTC, MedvedevBW commented
@placccebo

2018-01-25 03:59 UTC, placccebo requested changes

2018-01-25 03:59 UTC, placccebo commented on src/it/scala/com/bwsw/cloudstack/vault/server/vault/Constants.scala
> +  val policyNotFoundStatus = 404
remove "status" from the name

2018-01-25 05:18 UTC, MedvedevBW commented on src/it/scala/com/bwsw/cloudstack/vault/server/vault/Constants.scala
> +  val policyNotFoundStatus = 404
ok

2018-01-25 05:19 UTC, MedvedevBW commented
@placccebo

2018-01-25 05:47 UTC, placccebo approved these changes

2018-01-25 06:00 UTC, merged