CSVS-47 Meaningless pair was replaced to structure
bwsw/cs-vault-server pull request #73
Opened 2017-10-12 04:45 UTC by MedvedevBW

2017-10-13 03:15 UTC, placccebo submitted a review, later dismissed

2017-10-13 03:15 UTC, placccebo commented on src/main/scala/com/bwsw/cloudstack/vault/server/common/ProcessingEvent.scala
> +case class ProcessingEvent[T](process: Future[Unit], event: T)
case class ProcessingEventResult[T](event: T, result: Future[Unit])

2017-10-13 10:26 UTC, MedvedevBW commented on src/main/scala/com/bwsw/cloudstack/vault/server/common/ProcessingEvent.scala
> +case class ProcessingEvent[T](process: Future[Unit], event: T)
ok

2017-10-16 06:06 UTC, placccebo requested changes

2017-10-16 06:06 UTC, placccebo commented on src/test/scala/com/bwsw/cloudstack/vault/server/cloudstack/util/CloudStackEventHandlerTestSuite.scala
> +      case ProcessingEventResult(successHandleEvent, future) =>
successHandleEvent -> handledEvent

2017-10-16 06:23 UTC, MedvedevBW commented on src/test/scala/com/bwsw/cloudstack/vault/server/cloudstack/util/CloudStackEventHandlerTestSuite.scala
> +      case ProcessingEventResult(successHandleEvent, future) =>
ok

2017-10-16 06:24 UTC, placccebo approved these changes

2017-10-16 06:35 UTC, merged